#version 430 compatibility

layout (rgba32f, binding = 0) uniform image3D destTex;

layout( local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main()
{
	ivec3 dims = imageSize (destTex);
    ivec3 pixel_coords = ivec3(gl_GlobalInvocationID.xyz);
	
	highp float new_dim = float(dims.z);
	highp float temp = float(pixel_coords.z);

    imageStore (destTex, pixel_coords, vec4(0,0, 0 ,0));

}